openapi: 3.0.3
info:
  title: Social Feed API
  version: "1.0.0"
  description: |
    Мини-соцсеть для публикации постов, комментариев, оценок и подписок.

    Функциональные требования:
      - Публиковать посты.
      - Оставлять комментарии к постам.
      - Оценивать посты и комментарии других пользователей.
      - Подписываться на уведомления об активности (публикация постов) других пользователей.
      - Смотреть ленты других пользователей (DESC).
      - Смотреть агрегированную ленту из постов пользователей, на которых есть активная подписка.

    Нефункциональные требования (для справки):
      - DAU ≈ 10 000 000.
      - Регион: СНГ.
      - Availability: 99.99%.
      - Средний размер поста: ~5 MB.
      - Оценочная нагрузка: RPS ≈ 2 546.

servers:
  - url: https://api.example.com
    description: Production server (example)

tags:
  - name: post
    description: Работа с постами
  - name: comment
    description: Работа с комментариями
  - name: rating
    description: Оценки постов и комментариев
  - name: subscription
    description: Подписки на активность пользователей
  - name: feed
    description: Ленты новостей

paths:
  /v1/post:
    post:
      tags: [post]
      summary: Публикация поста
      description: |
        Пользователь публикует новый пост. Поддерживает загрузку медиа (до ~5 MB).
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: integer
                  format: int64
                  example: 1
                  description: ID автора поста.
                text:
                  type: string
                  description: Текст поста.
                media:
                  type: string
                  format: binary
                  description: Файл изображения/видео (опционально).
      responses:
        "201":
          description: Пост успешно создан.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/comment/{post_id}:
    post:
      tags: [comment]
      summary: Создание комментария к посту
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID поста, к которому оставляется комментарий.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  example: "go v cs"
                  description: Текст комментария.
                user_id:
                  type: integer
                  format: int64
                  description: ID автора комментария.
      responses:
        "201":
          description: Комментарий создан.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "400":
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Пост не найден.

  /v1/post/rating/{post_id}:
    put:
      tags: [rating]
      summary: Оценка поста
      description: Пользователь ставит лайк/дизлайк посту.
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID поста для оценки.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RatingRequest"
      responses:
        "200":
          description: Оценка поста обновлена.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RatingResponse"
        "400":
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Пост не найден.

  /v1/comment/rating/{comment_id}:
    put:
      tags: [rating]
      summary: Оценка комментария
      description: Пользователь ставит лайк/дизлайк комментарию.
      parameters:
        - name: comment_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID комментария для оценки.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RatingRequest"
      responses:
        "200":
          description: Оценка комментария обновлена.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RatingResponse"
        "400":
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Комментарий не найден.

  /v1/subscribe/activity/{user_id}:
    post:
      tags: [subscription]
      summary: Подписка на активность пользователя
      description: |
        Подписаться или отписаться от уведомлений об активности (новые посты) указанного пользователя.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID пользователя, на которого оформляется подписка.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                subscribe:
                  type: boolean
                  default: true
                  description: true — подписаться, false — отписаться.
      responses:
        "200":
          description: Статус подписки обновлён.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionStatus"
        "400":
          description: Неверный запрос.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Пользователь не найден.

  /v1/feed/{user_id}:
    get:
      tags: [feed]
      summary: Лента постов пользователя
      description: |
        Возвращает ленту постов конкретного пользователя.
        Поддерживает сортировку по дате (DESC/ASC). По требованиям — DESC по умолчанию.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID пользователя, чью ленту просматриваем.
        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Порядок сортировки по дате создания поста.
        - name: page-num
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Номер страницы (пагинация по ~20 постов).
        - name: page-size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Количество постов на странице.
      responses:
        "200":
          description: Лента пользователя.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedPage"
        "404":
          description: Пользователь не найден.

  /v1/feed/subscribers:
    get:
      tags: [feed]
      summary: Агрегированная лента подписок
      description: |
        Возвращает агрегированную ленту из постов пользователей, на которых есть активная подписка.
      parameters:
        - name: page-num
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Номер страницы.
        - name: page-size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 21
          description: Количество постов на странице. В примере — 21.
      responses:
        "200":
          description: Агрегированная лента подписок.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedPage"

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        text:
          type: string
        media_url:
          type: string
          format: uri
          nullable: true
        created_at:
          type: string
          format: date-time
        rating:
          type: integer
          description: Суммарный рейтинг поста (лайки - дизлайки).
      required: [id, user_id, text, created_at]

    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        post_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        message:
          type: string
        created_at:
          type: string
          format: date-time
        rating:
          type: integer
          description: Суммарный рейтинг комментария.
      required: [id, post_id, user_id, message, created_at]

    RatingRequest:
      type: object
      description: Запрос на выставление оценки.
      required:
        - user_id
        - value
      properties:
        user_id:
          type: integer
          format: int64
          description: ID пользователя, ставящего оценку.
        value:
          type: integer
          enum: [-1, 1]
          description: |
            Значение оценки: 1 — лайк, -1 — дизлайк.

    RatingResponse:
      type: object
      properties:
        total_rating:
          type: integer
          description: Новый суммарный рейтинг сущности.
      required: [total_rating]

    SubscriptionStatus:
      type: object
      properties:
        target_user_id:
          type: integer
          format: int64
        subscribed:
          type: boolean
          description: Текущий статус подписки после операции.
      required: [target_user_id, subscribed]

    FeedItem:
      type: object
      description: Элемент ленты (пост + базовая информация об авторе).
      properties:
        post:
          $ref: "#/components/schemas/Post"
        author:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
          required: [id]
      required: [post]

    FeedPage:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/FeedItem"
        page_num:
          type: integer
        page_size:
          type: integer
        total:
          type: integer
          description: Общее количество элементов (может быть приблизительным).
      required: [items, page_num, page_size]

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required: [code, message]